# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTumblrApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTumblrApp
  pod 'AFNetworking', '~> 2.6'

  target 'MyTumblrAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTumblrAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
